import BestFriends from '../../../assets/images/best-friends.png';
import ChatBubble from '../../../assets/images/chat-bubble.png';
import CheckItOut from '../../../assets/images/check-it-out.png';
import CheckItOut2 from '../../../assets/images/check-it-out2.png';
import Checked from '../../../assets/images/checked.png';
import FollowUs from '../../../assets/images/follow-us.png';
import FollowUs2 from '../../../assets/images/follow-us2.png';
import GoldStar from '../../../assets/images/gold-star.png';
import GreatJob from '../../../assets/images/great-job.png';
import Hashtag from '../../../assets/images/hashtag.png';
import Heart from '../../../assets/images/heart.png';
import Love from '../../../assets/images/love.png';
import Arm1 from '../../../assets/images/arm1.png';
import Arm2 from '../../../assets/images/arm2.png';
import Arm3 from '../../../assets/images/arm3.png';
import Kargin1 from '../../../assets/images/kargin1.png';
import Kargin2 from '../../../assets/images/kargin2.png';
import Kargin3 from '../../../assets/images/kargin3.png';
import Kargin4 from '../../../assets/images/kargin4.png';
import Kargin5 from '../../../assets/images/kargin5.png';
import Kargin6 from '../../../assets/images/kargin6.png';
import Kargin7 from '../../../assets/images/kargin7.png';
import {ISticker} from '../models/interface/sticker.interface';

export const stickersData: ISticker[] = [
  {
    id: 1,
    path: BestFriends,
    name: 'best-friends',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 2,
    path: ChatBubble,
    name: 'chat-bubble',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 3,
    path: CheckItOut,
    name: 'check-it-out',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 4,
    path: CheckItOut2,
    name: 'check-it-out (1)',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 5,
    path: Checked,
    name: 'checked',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 6,
    path: FollowUs,
    name: 'follow-us (1)',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 7,
    path: FollowUs2,
    name: 'follow-us (1)',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 8,
    path: GoldStar,
    name: 'gold-star',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 9,
    path: GreatJob,
    name: 'great-job',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 10,
    path: Hashtag,
    name: 'hashtag (1)',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 11,
    path: Heart,
    name: 'heart',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 12,
    path: Love,
    name: 'love',
    keyword: [
      'instagram',
      'hi',
      'hello',
      'happy',
      'follow',
      'like',
      'new',
      'post',
      'insta',
      'reels',
      'birthday',
      'happy',
      'love',
    ],
  },
  {
    id: 13,
    path: Arm1,
    name: '736048754',
    keyword: ['hi', 'ok', 'hello', 'armenian', 'hayeren', 'barev'],
  },
  {
    id: 14,
    path: Arm2,
    name: '2118427687',
    keyword: ['hi', 'ok', 'hello', 'armenian', 'hayeren', 'barev'],
  },
  {
    id: 15,
    path: Arm3,
    name: '702603190',
    keyword: ['hi', 'ok', 'hello', 'armenian', 'hayeren', 'barev'],
  },
  {
    id: 16,
    path: Kargin1,
    name: 'file_130140786',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 17,
    path: Kargin2,
    name: 'file_130140779',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 18,
    path: Kargin3,
    name: 'file_130140751',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 19,
    path: Kargin4,
    name: 'file_130140745',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 20,
    path: Kargin5,
    name: 'file_130140753',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 21,
    path: Kargin6,
    name: 'file_130140747',
    keyword: ['karginstickers', 'kargin', 'karg', 'haxordum'],
  },
  {
    id: 22,
    path: Kargin7,
    name: 'file_130140790',
    keyword: ['karginstickers', 'kargin', 'karg'],
  },
];
